services:
  db:
    image: postgres:latest
    container_name: postgres-administrativo
    environment:
      POSTGRES_DB: administrativo
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d postgres" ]
        interval: 30s
        timeout: 10s
        retries: 5


volumes:
  postgres_data:
